# Custom Language File for Launcher Customizer

[ejs.app]
title = "Allegator Games Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/nickallegator/CEHeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"
mediaPatreonURL = "https://patreon.com/AllegatorGames?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink"

[ejs.settings]
sourceGithubLink = "https://github.com/nickallegator/CEHeliosLauncher"
supportLink = "https://github.com/nickallegator/CEHeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO AG LAUNCHER"
welcomeDescription = "The Allegator Games Launcher keeps official modpacks, tested dependencies, optional integrations, updates, and community creations together in one workshop."
welcomeDescCTA = "Sign in with Microsoft to prepare your first Allegator Games profile."
